---
- hosts: localhost
  tasks:
  - name: Check git folder
    file:
      state: directory
      path: /home/awx/git
  - name: Check archive folder
    file:
      state: directory
      path: /home/awx/archive
  - name: Check dist archive folder
    file:
      state: directory
      path: /home/awx/archive/dists
  - name: Check rpm archive folder
    file:
      state: directory
      path: /home/awx/archive/rpms
  - name: Checkout AWX from Git
    git:
      repo: 'https://github.com/ansible/awx.git'
      dest: /home/awx/git/awx
      version: "devel"
  - name: Get AWX version from GIT
    shell: cd /home/awx/git/awx && git describe --long --first-parent |cut -f1-2 -d- |sed 's/-/./'
    register: awx_version
  - name: Check if build exists
    stat: 
      path: /home/awx/archive/dists/awx-{{ awx_version.stdout }}.tar.gz
    register: build
  - name: "Artifact URL of test results to Tower Workflows"
    set_stats:
      data:
        build_exists: "{{ build.stat.exists}}"
        release: "{{ awx_version.stdout }}"
  