---
- hosts: all
  tasks:
  - name: Send SRPM to Fedora COPR
    shell: /home/awx/bin/send-build awx-{{ release }}-1.el7.centos.src.rpm /home/awx/archive/rpms/awx-{{ release }}-1.el7.centos.src.rpm
    when: build_exists == false