---
- hosts: all
  tasks:
  - mail:
      subject: 'AWX RPM Auto Build Version {{ release }}' 
      to: "m@rtinjuhl.dk"
      body: |
        New version of AWX has been build and pushed to COPR:

        Release Version: {{ release }}
    delegate_to: localhost
    when: build_exists == false
